# Generated by Django 4.1.7 on 2023-03-13 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='dept_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
